version: '3.2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    container_name: dropout_app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: postgres
    env_file:
      - .env